# Generated by Django 2.2.3 on 2019-08-05 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('is_premium', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('link', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visual', models.IntegerField()),
                ('fun', models.IntegerField()),
                ('manner', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Place')),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='place_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PlaceType'),
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('appeal', models.TextField()),
                ('is_matched', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('man', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_man', to=settings.AUTH_USER_MODEL)),
                ('meeting_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.MeetingType')),
                ('openby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_openby', to=settings.AUTH_USER_MODEL)),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Place')),
                ('rating', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Rating')),
                ('woman', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_woman', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
