# Generated by Django 2.2.3 on 2019-09-02 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_meeting_place_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='place_Type',
            new_name='place_type',
        ),
    ]
