# Generated by Django 2.2.3 on 2019-09-02 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190902_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_place', to='core.Place'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='place_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_place_type', to='core.PlaceType'),
        ),
    ]
