# Generated by Django 2.2.3 on 2019-09-09 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190903_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='man',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='woman',
        ),
        migrations.CreateModel(
            name='MatchRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_selected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_receiver', to='core.Meeting')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_sender', to='core.Meeting')),
            ],
        ),
    ]
