# Generated by Django 2.2.3 on 2019-09-10 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190909_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_place', to='core.Place'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Rating'),
        ),
    ]
