# Generated by Django 2.2.3 on 2019-09-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190911_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchrequest',
            name='is_declined',
            field=models.BooleanField(default=False),
        ),
    ]
