# Generated by Django 2.2.3 on 2019-10-01 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190930_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
