# Generated by Django 2.2.3 on 2019-10-02 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rating_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='rating',
        ),
        migrations.AddField(
            model_name='rating',
            name='meeting',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Meeting'),
        ),
    ]
