# Generated by Django 2.2.3 on 2019-10-08 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20191002_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='rating',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_rating', to='core.Rating'),
        ),
    ]
