# Generated by Django 2.2.3 on 2019-10-20 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20191020_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchrequest',
            name='accepted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='matchrequest',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_manager', to=settings.AUTH_USER_MODEL),
        ),
    ]
