# Generated by Django 2.2.3 on 2019-10-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20191020_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchrequest',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
