# Generated by Django 2.2.3 on 2019-11-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20191026_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchrequest',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
