# Generated by Django 2.2.3 on 2019-11-13 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20191113_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchrequest',
            name='is_canceled',
        ),
        migrations.AlterField(
            model_name='matchrequest',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_receiver', to='core.Meeting'),
        ),
        migrations.AlterField(
            model_name='matchrequest',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_sender', to='core.Meeting'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='matched_meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_matched', to='core.Meeting'),
        ),
    ]
