# Generated by Django 2.2.3 on 2019-11-13 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20191113_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchrequest',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_receiver', to='core.Meeting'),
        ),
        migrations.AlterField(
            model_name='matchrequest',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_sender', to='core.Meeting'),
        ),
    ]
