# Generated by Django 2.2.3 on 2019-11-20 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20191113_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='fun',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='manner',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='visual',
        ),
    ]
