# Generated by Django 2.2.3 on 2019-12-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20191120_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchrequest',
            name='manager_call',
            field=models.BooleanField(default=False),
        ),
    ]
