# Generated by Django 2.2.3 on 2019-08-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_certified',
            field=models.BooleanField(default=False),
        ),
    ]
