# Generated by Django 2.2.3 on 2019-08-29 13:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0005_user_is_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=14, null=True, validators=[django.core.validators.RegexValidator(message='Phone number is invalid.', regex='d{3}[-]?\\d{4}[-]?\\d{4}')], verbose_name='phone number'),
        ),
    ]
