# Generated by Django 2.2.3 on 2019-08-29 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0007_auto_20190829_2234'),
        ('authorization', '0004_auto_20190822_2344'),
    ]

    operations = [
    ]
