# Generated by Django 2.2.3 on 2019-08-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0009_auto_20190830_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
