# Generated by Django 2.2.3 on 2019-08-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0011_auto_20190830_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=70),
        ),
    ]
