# Generated by Django 2.2.3 on 2019-10-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0014_user_firebase_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='firebase_token',
            field=models.CharField(max_length=1000, null=True, unique=True),
        ),
    ]
