# Generated by Django 2.2.3 on 2019-10-16 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0015_auto_20191015_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
