# Generated by Django 2.2.3 on 2019-11-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0016_user_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cert_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
