# Generated by Django 2.2.3 on 2019-11-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0017_user_cert_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cert_image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
