
# Generated by Django 2.2.3 on 2019-11-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0019_auto_20191113_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ticket',
            field=models.IntegerField(default=0),
        ),
    ]

