# Generated by Django 2.2.3 on 2019-12-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0022_auto_20191204_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invite_code',
            field=models.CharField(max_length=6, null=True, unique=True),
        ),
    ]
